export const MOCK_DATA = [
  {
    id: 1,
    first_name: "Fidelio",
    last_name: "Ousby",
    email: "fousby0@unicef.org",
    gender: "Male",
  },
  {
    id: 2,
    first_name: "Lovell",
    last_name: "Coats",
    email: "lcoats1@loc.gov",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Lon",
    last_name: "McNish",
    email: "lmcnish2@symantec.com",
    gender: "Male",
  },
  {
    id: 4,
    first_name: "Charlene",
    last_name: "Battill",
    email: "cbattill3@auda.org.au",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Phillida",
    last_name: "Slaght",
    email: "pslaght4@wiley.com",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Roxy",
    last_name: "Coch",
    email: "rcoch5@imdb.com",
    gender: "Female",
  },
  {
    id: 7,
    first_name: "Layla",
    last_name: "Kubyszek",
    email: "lkubyszek6@nationalgeographic.com",
    gender: "Female",
  },
  {
    id: 8,
    first_name: "Ellsworth",
    last_name: "Binnie",
    email: "ebinnie7@foxnews.com",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Conny",
    last_name: "Varns",
    email: "cvarns8@dailymail.co.uk",
    gender: "Polygender",
  },
  {
    id: 10,
    first_name: "Jeromy",
    last_name: "Fellnee",
    email: "jfellnee9@springer.com",
    gender: "Male",
  },
  {
    id: 11,
    first_name: "Zacharia",
    last_name: "Caldow",
    email: "zcaldowa@live.com",
    gender: "Male",
  },
  {
    id: 12,
    first_name: "Sissie",
    last_name: "Roobottom",
    email: "sroobottomb@cocolog-nifty.com",
    gender: "Female",
  },
  {
    id: 13,
    first_name: "Peria",
    last_name: "Wharlton",
    email: "pwharltonc@chron.com",
    gender: "Female",
  },
  {
    id: 14,
    first_name: "Lyon",
    last_name: "Kleinstub",
    email: "lkleinstubd@yellowbook.com",
    gender: "Male",
  },
  {
    id: 15,
    first_name: "Farris",
    last_name: "Cheeney",
    email: "fcheeneye@virginia.edu",
    gender: "Male",
  },
  {
    id: 16,
    first_name: "Felike",
    last_name: "Mapson",
    email: "fmapsonf@bing.com",
    gender: "Polygender",
  },
  {
    id: 17,
    first_name: "Gareth",
    last_name: "Sparkwill",
    email: "gsparkwillg@paginegialle.it",
    gender: "Male",
  },
  {
    id: 18,
    first_name: "Ogden",
    last_name: "Cheese",
    email: "ocheeseh@goo.ne.jp",
    gender: "Male",
  },
  {
    id: 19,
    first_name: "Melanie",
    last_name: "Isaac",
    email: "misaaci@who.int",
    gender: "Female",
  },
  {
    id: 20,
    first_name: "Flossie",
    last_name: "Gippes",
    email: "fgippesj@reuters.com",
    gender: "Female",
  },
  {
    id: 21,
    first_name: "Ruttger",
    last_name: "Dillintone",
    email: "rdillintonek@aboutads.info",
    gender: "Male",
  },
  {
    id: 22,
    first_name: "Lennie",
    last_name: "Budibent",
    email: "lbudibentl@t-online.de",
    gender: "Male",
  },
  {
    id: 23,
    first_name: "Jackie",
    last_name: "Balchin",
    email: "jbalchinm@netlog.com",
    gender: "Female",
  },
  {
    id: 24,
    first_name: "Annabell",
    last_name: "Hartland",
    email: "ahartlandn@mac.com",
    gender: "Female",
  },
  {
    id: 25,
    first_name: "Malva",
    last_name: "Fane",
    email: "mfaneo@netvibes.com",
    gender: "Female",
  },
  {
    id: 26,
    first_name: "Tommy",
    last_name: "Pittwood",
    email: "tpittwoodp@fc2.com",
    gender: "Genderqueer",
  },
  {
    id: 27,
    first_name: "Margaretha",
    last_name: "Clemits",
    email: "mclemitsq@rambler.ru",
    gender: "Female",
  },
  {
    id: 28,
    first_name: "Van",
    last_name: "Barcroft",
    email: "vbarcroftr@answers.com",
    gender: "Female",
  },
  {
    id: 29,
    first_name: "Peria",
    last_name: "Croote",
    email: "pcrootes@tiny.cc",
    gender: "Female",
  },
  {
    id: 30,
    first_name: "Theo",
    last_name: "Pillifant",
    email: "tpillifantt@dropbox.com",
    gender: "Genderqueer",
  },
];
